[locate]
metadata_dir_name = '.catkin_tools'

profiles_yml_file_name = 'profiles.yaml'

default_profile_name = 'default'

[rospack]
rospack_command = "rospack"

[build]
ignore_dirs = ["build", "catkin_tools_prebuild"]

[symlink]
compile_commands_name = "compile_commands.json"
